---
- include: install_httpd.yml
- include: copy_code.yml
lstld4abg8wm-m:web s0043411$ cat tasks/install_httpd.yml
---
# These tasks install http and the php modules.

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   
- name: http service state
  service: name=httpd state=started enabled=yes